monthly_events_by_year = {
    "2017": {
        1: ["Tahun Baru Masehi", "Tahun Baru Imlek"],
        2: ["Hari Valentine"],
        3: ["Hari Raya Nyepi", "Ulang Tahun Lazada"],
        4: ["Wafat Isa Almasih", "Isra Mi'raj"],
        5: ["Hari Buruh", "Kenaikan Isa Almasih", "Awal Bulan Ramadan"],
        6: ["Hari Lahir Pancasila", "Puncak Ramadan & Libur Idul Fitri"],
        7: ["Periode Back to School"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia"],
        9: ["Harbolnas 9.9", "Hari Raya Idul Adha", "Tahun Baru Islam"],
        10: ["Harbolnas 10.10"],
        11: ["Harbolnas 11.11"],
        12: ["Harbolnas 12.12", "Maulid Nabi", "Hari Ibu", "Libur Natal"],
    },
    "2018": {
        1: ["Tahun Baru Masehi"],
        2: ["Tahun Baru Imlek", "Hari Valentine"],
        3: ["Hari Raya Nyepi", "Wafat Isa Almasih", "Ulang Tahun Lazada"],
        4: ["Isra Mi'raj"],
        5: ["Hari Buruh", "Kenaikan Isa Almasih", "Awal Bulan Ramadan", "Hari Raya Waisak"],
        6: ["Hari Lahir Pancasila", "Puncak Ramadan & Libur Idul Fitri"],
        7: ["Periode Back to School"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia", "Hari Raya Idul Adha"],
        9: ["Harbolnas 9.9", "Tahun Baru Islam"],
        10: ["Harbolnas 10.10"],
        11: ["Harbolnas 11.11", "Maulid Nabi"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    },
    "2019": {
        1: ["Tahun Baru Masehi"],
        2: ["Tahun Baru Imlek", "Hari Valentine"],
        3: ["Hari Raya Nyepi", "Ulang Tahun Lazada"],
        4: ["Isra Mi'raj", "Wafat Isa Almasih"],
        5: ["Hari Buruh", "Awal Bulan Ramadan", "Hari Raya Waisak", "Kenaikan Isa Almasih"],
        6: ["Hari Lahir Pancasila", "Puncak Ramadan & Libur Idul Fitri"],
        7: ["Periode Back to School"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia", "Hari Raya Idul Adha"],
        9: ["Harbolnas 9.9", "Tahun Baru Islam"],
        10: ["Harbolnas 10.10"],
        11: ["Harbolnas 11.11", "Maulid Nabi"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    },
    "2020": {
        1: ["Tahun Baru Masehi", "Tahun Baru Imlek"],
        2: ["Hari Valentine"],
        3: ["Hari Raya Nyepi", "Ulang Tahun Lazada"],
        4: ["Wafat Isa Almasih", "Awal Bulan Ramadan"],
        5: ["Hari Buruh", "Hari Raya Waisak", "Kenaikan Isa Almasih", "Puncak Ramadan & Libur Idul Fitri"],
        6: ["Hari Lahir Pancasila"],
        7: ["Periode Back to School", "Hari Raya Idul Adha"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia", "Tahun Baru Islam"],
        9: ["Harbolnas 9.9"],
        10: ["Harbolnas 10.10", "Maulid Nabi"],
        11: ["Harbolnas 11.11"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    },
    "2021": {
        1: ["Tahun Baru Masehi"],
        2: ["Tahun Baru Imlek", "Hari Valentine"],
        3: ["Isra Mi'raj", "Hari Raya Nyepi", "Ulang Tahun Lazada"],
        4: ["Wafat Isa Almasih", "Awal Bulan Ramadan"],
        5: ["Hari Buruh", "Puncak Ramadan & Libur Idul Fitri", "Kenaikan Isa Almasih", "Hari Raya Waisak"],
        6: ["Hari Lahir Pancasila"],
        7: ["Periode Back to School", "Hari Raya Idul Adha"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia", "Tahun Baru Islam"],
        9: ["Harbolnas 9.9"],
        10: ["Harbolnas 10.10", "Maulid Nabi"],
        11: ["Harbolnas 11.11"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    },
    "2022": {
        1: ["Tahun Baru Masehi"],
        2: ["Tahun Baru Imlek", "Isra Mi'raj", "Hari Valentine"],
        3: ["Hari Raya Nyepi", "Ulang Tahun Lazada"],
        4: ["Awal Bulan Ramadan", "Wafat Isa Almasih"],
        5: ["Hari Buruh", "Puncak Ramadan & Libur Idul Fitri", "Hari Raya Waisak", "Kenaikan Isa Almasih"],
        6: ["Hari Lahir Pancasila"],
        7: ["Periode Back to School", "Hari Raya Idul Adha", "Tahun Baru Islam"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia"],
        9: ["Harbolnas 9.9"],
        10: ["Harbolnas 10.10", "Maulid Nabi"],
        11: ["Harbolnas 11.11"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    },
    "2023": {
        1: ["Tahun Baru Masehi", "Tahun Baru Imlek"],
        2: ["Isra Mi'raj", "Hari Valentine"],
        3: ["Hari Raya Nyepi", "Awal Bulan Ramadan", "Ulang Tahun Lazada"],
        4: ["Wafat Isa Almasih", "Puncak Ramadan & Libur Idul Fitri"],
        5: ["Hari Buruh", "Kenaikan Isa Almasih"],
        6: ["Hari Lahir Pancasila", "Hari Raya Waisak", "Hari Raya Idul Adha"],
        7: ["Periode Back to School", "Tahun Baru Islam"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia"],
        9: ["Harbolnas 9.9", "Maulid Nabi"],
        10: ["Harbolnas 10.10"],
        11: ["Harbolnas 11.11"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    },
    "2024": {
        1: ["Tahun Baru Masehi"],
        2: ["Isra Mi'raj", "Tahun Baru Imlek", "Hari Valentine"],
        3: ["Hari Raya Nyepi", "Awal Bulan Ramadan", "Wafat Isa Almasih", "Ulang Tahun Lazada"],
        4: ["Puncak Ramadan & Libur Idul Fitri"],
        5: ["Hari Buruh", "Kenaikan Isa Almasih", "Hari Raya Waisak"],
        6: ["Hari Lahir Pancasila", "Hari Raya Idul Adha"],
        7: ["Periode Back to School", "Tahun Baru Islam"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia"],
        9: ["Harbolnas 9.9", "Maulid Nabi"],
        10: ["Harbolnas 10.10"],
        11: ["Harbolnas 11.11"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    },
    "2025": {
        1: ["Tahun Baru Masehi", "Isra Mi'raj", "Tahun Baru Imlek"],
        2: ["Hari Valentine"],
        3: ["Awal Bulan Ramadan", "Hari Raya Nyepi", "Ulang Tahun Lazada"],
        4: ["Puncak Ramadan & Libur Idul Fitri", "Wafat Isa Almasih"],
        5: ["Hari Buruh", "Hari Raya Waisak", "Kenaikan Isa Almasih"],
        6: ["Hari Lahir Pancasila", "Hari Raya Idul Adha", "Tahun Baru Islam"],
        7: ["Periode Back to School"],
        8: ["Hari Kemerdekaan RI", "Ulang Tahun Tokopedia"],
        9: ["Harbolnas 9.9", "Maulid Nabi"],
        10: ["Harbolnas 10.10"],
        11: ["Harbolnas 11.11"],
        12: ["Harbolnas 12.12", "Hari Ibu", "Libur Natal"],
    }
}